[package]
name = "d10"
version = "0.1.0"
edition = "2024"

#[build]
#rustflags = [
#    "-C", "opt-level=3",
#    "-C", "target-cpu=native",
#    "-C", "lto=fat",
#    "-C", "codegen-units=1",
#    "-C", "strip=symbols",
#]

[dependencies]
